### ISSUE TITLE
Hi,if the MemSAC can used in unsupervised Semantic Segmentation

### ISSUE THREAD

**Issue by yuheyuan** [ViLab-UCSD/MemSAC_ECCV2022#1]

**Comment by yuheyuan** [comment]
I'm interested in this work and I want to know if it is possible to fusion this MemSAC to semantic

**Comment by tarun005** [comment]
Hi, if your question is if MemSAC can be applied to adaptation on semantic segmentation datasets, I think yes. It can be done. We haven't tried it because we did not find a suitable dataset with many-classes for segmentation, but it should be possible.
